function [rms1, rms2] = CreateColoredRectangleOnAxes(audiodata, axes, timeStart, timeEnd, color)
%  get RMS values to match rise or fall
    rms1 = EstimateRMS(audiodata(1:round(end/2)));
    rms2 = EstimateRMS(audiodata(round(end/2):end));
%  create colored rectangles
    ylim = get(axes, 'YLim');            
        if  rms1 > ylim(2) || rms2 > ylim(2)
            set(axes, 'YLim', [ylim(1), max(rms1, rms2)])
        end
    x = [timeStart timeStart timeEnd timeEnd];
    y = [0 rms1 rms2 0];
    patch(axes, x, y, color)
    
    annotation('textbox',...
        [0.81 0.68 0.1 0.25],...
        'String',{'Joy - yellow',...
                'Negative - red',...
                'Neutral - green',...
                'Sadness - blue',...
                'Beep - black',...
                  });
end